#!/usr/bin/env bash

sudo qemu-system-x86_64 -m 2048 \
                        -enable-kvm \
                        -vga qxl \
                        -drive file=$HOME/../paradise/Projects/AndroidWS/images/android-vol.img,format=raw \
			                  -drive if=pflash,format=raw,readonly=on,file=$HOME/.fa/src/guix-config/per-user/s/profiles/90-heavy/profiles.d/profile/share/firmware/ovmf_code_x64.bin \
                        -drive if=pflash,format=raw,file=$HOME/../paradise/Projects/AndroidWS/OVMF_VARS.fd \
                        -device qemu-xhci,id=usb \
                        -device usb-kbd \
                        -device usb-tablet \
                        -device virtio-serial  \
                        -spice port=5930,disable-ticketing=on \
                        -chardev spicevmc,id=spicechannel0,name=vdagent \
                        -device virtserialport,chardev=spicechannel0,name=com.redhat.spice.0 \
                        -device qxl \
                        -display sdl,gl=on -vga qxl
# -display spice-app



# -display gtk \
# -vga std \
