#!/usr/bin/env bash

sudo qemu-system-x86_64 -m 2048 \
                        -enable-kvm \
                        -vga std \
                        -display gtk \
                        -drive file=android-vol.img,format=raw \
			                  -drive if=pflash,format=raw,readonly=on,file=$HOME/.fa/src/guix-config/per-user/s/profiles/90-heavy/profiles.d/profile/share/firmware/ovmf_code_x64.bin \
                        -drive if=pflash,format=raw,file=OVMF_VARS.fd \
                        -device qemu-xhci,id=usb \
                        -device usb-kbd \
                        -device usb-tablet


